#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path

from bio_fly.inverse_motor_fit import fit_inverse_motor_interface
from bio_fly.paths import DEFAULT_OUTPUT_ROOT


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit an auditable surrogate DN-to-motor interface from connectome readouts.")
    parser.add_argument(
        "--connectome-summary",
        type=Path,
        default=DEFAULT_OUTPUT_ROOT / "eon_multimodal_benchmark" / "connectome_readout" / "connectome_multimodal_readout_summary.csv",
        help="CSV generated by run_eon_multimodal_benchmark.py connectome readout.",
    )
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_ROOT / "inverse_motor_fit")
    parser.add_argument("--target-table", type=Path, default=None, help="Optional external calibration table with motor target columns.")
    parser.add_argument("--alpha", type=float, default=0.2, help="Ridge regularization strength.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    paths = fit_inverse_motor_interface(
        connectome_summary_path=args.connectome_summary,
        output_dir=args.output_dir,
        target_table_path=args.target_table,
        alpha=args.alpha,
    )
    print(json.dumps({key: str(value) for key, value in paths.__dict__.items()}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()

